[Interface]
ListenPort = 51820
SaveConfig = false
### Interface start and setup
PostUp = ip addr add ${ext_ip_nm} dev ${ext_if}
PostUp = ip link set dev ${ext_if} up
PostUp = ip route add default via ${ext_gw} dev ${ext_if}
PostUp = iptables -P INPUT DROP
PostUp = iptables -P FORWARD DROP
PostUp = ip6tables -P INPUT DROP
PostUp = ip6tables -P FORWARD DROP
PostUp = iptables -A INPUT -i %i -p icmp -m icmp --icmp-type 8 -j ACCEPT
PostUp = ip6tables -A INPUT -i %i -p ipv6-icmp -j ACCEPT
PostUp = iptables -A FORWARD -i %i -p tcp -m multiport --dports 25,137,139 -j DROP
PostUp = iptables -A FORWARD -i %i -p udp -m multiport --dports 137,138 -j DROP
PostUp = ip6tables -A FORWARD -i %i -p tcp -m multiport --dports 25,137,139 -j DROP
PostUp = ip6tables -A FORWARD -i %i -p udp -m multiport --dports 137,138 -j DROP
PostUp = iptables -A FORWARD -i %i -o ${ext_if} -j ACCEPT
PostUp = iptables -A FORWARD -o %i -i ${ext_if} -j ACCEPT
PostUp = ip6tables -A FORWARD -i %i -o ${ext_if} -j ACCEPT
PostUp = ip6tables -A FORWARD -o %i -i ${ext_if} -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o ${ext_if} -j MASQUERADE
PostUp = ip6tables -t nat -A POSTROUTING -o ${ext_if} -j MASQUERADE
PostUp = iptables -A INPUT -d ${ext_ip} -p udp -m udp --dport 51820 -j ACCEPT
PostUp = iptables -t nat -A PREROUTING -i %i -p udp --dport 53 -j DNAT --to 1.1.1.1
PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport 53 -j DNAT --to 1.1.1.1
PostUp = ip6tables -t nat -A PREROUTING -i %i -p udp --dport 53 -j DNAT --to 2606:4700:4700::1111
PostUp = ip6tables -t nat -A PREROUTING -i %i -p tcp --dport 53 -j DNAT --to 2606:4700:4700::1111
# Traffic control
PostUp = tc qdisc add dev %i root handle 1: htb
PostUp = tc qdisc add dev %i handle ffff: ingress
PostUp = tc filter add dev %i parent 1:0 prio 1 protocol ip u32
PostUp = tc filter add dev %i parent 1:0 prio 1 handle 2: protocol ip u32 divisor 256
PostUp = tc filter add dev %i parent 1:0 prio 1 protocol ip u32 ht 800:: match ip dst 172.16.0.0/16 hashkey mask 0x000000ff at 16 link 2:
PostUp = tc filter add dev %i parent ffff:0 prio 1 protocol ip u32
PostUp = tc filter add dev %i parent ffff:0 prio 1 handle 3: protocol ip u32 divisor 256
PostUp = tc filter add dev %i parent ffff:0 prio 1 protocol ip u32 ht 800:: match ip src 172.16.0.0/16 hashkey mask 0x000000ff at 12 link 3:
# Torrent blocking
PostUp = ipset create UserP2Pv4%i hash:ip family inet timeout 86400
PostUp = ipset create UserP2Pv6%i hash:ip family inet6 timeout 86400
PostUp = iptables -N FORWARD_P2P_TO_VETH_%i
PostUp = iptables -N FORWARD_P2P_TO_WG_%i
PostUp = iptables -N FORWARD_USER_P2P_TO_VETH_%i
PostUp = iptables -N FORWARD_USER_P2P_TO_WG_%i
PostUp = ip6tables -N FORWARD_P2P_TO_VETH_%i
PostUp = ip6tables -N FORWARD_P2P_TO_WG_%i
PostUp = ip6tables -N FORWARD_USER_P2P_TO_VETH_%i
PostUp = ip6tables -N FORWARD_USER_P2P_TO_WG_%i
PostUp = iptables -I FORWARD 1 -i %i -o ${ext_if} -m ipp2p --bit -g FORWARD_P2P_TO_VETH_%i
PostUp = iptables -I FORWARD 2 -i %i -o ${ext_if} -m set --match-set UserP2Pv4%i src -g FORWARD_USER_P2P_TO_VETH_%i
PostUp = iptables -I FORWARD 3 -o %i -i ${ext_if} -m ipp2p --bit -g FORWARD_P2P_TO_WG_%i
PostUp = iptables -I FORWARD 4 -o %i -i ${ext_if} -m set --match-set UserP2Pv4%i dst -g FORWARD_USER_P2P_TO_WG_%i
PostUp = ip6tables -I FORWARD 1 -i %i -o ${ext_if} -m ipp2p --bit -g FORWARD_P2P_TO_VETH_%i
PostUp = ip6tables -I FORWARD 2 -i %i -o ${ext_if} -m set --match-set UserP2Pv6%i src -g FORWARD_USER_P2P_TO_VETH_%i
PostUp = ip6tables -I FORWARD 3 -o %i -i ${ext_if} -m ipp2p --bit -g FORWARD_P2P_TO_WG_%i
PostUp = ip6tables -I FORWARD 4 -o %i -i ${ext_if} -m set --match-set UserP2Pv6%i dst -g FORWARD_USER_P2P_TO_WG_%i
PostUp = iptables -A FORWARD_P2P_TO_VETH_%i -j SET --add-set UserP2Pv4%i src --exist
PostUp = iptables -A FORWARD_P2P_TO_VETH_%i -j NFLOG --nflog-prefix FORWARD_P2P_TO_VETH_%i --nflog-group 2 --nflog-size 1500 --nflog-threshold 64
PostUp = iptables -A FORWARD_P2P_TO_VETH_%i -j REJECT --reject-with icmp-admin-prohibited
PostUp = iptables -A FORWARD_P2P_TO_WG_%i -j SET --add-set UserP2Pv4%i dst --exist
PostUp = iptables -A FORWARD_P2P_TO_WG_%i -j NFLOG --nflog-prefix FORWARD_P2P_TO_WG_%i --nflog-group 3 --nflog-size 1500 --nflog-threshold 64
PostUp = iptables -A FORWARD_P2P_TO_WG_%i -j DROP
PostUp = iptables -A FORWARD_USER_P2P_TO_VETH_%i -p tcp -m multiport --dports 53,80,443 -j ACCEPT
PostUp = iptables -A FORWARD_USER_P2P_TO_VETH_%i -p udp -m multiport --dports 53,443 -j ACCEPT
PostUp = iptables -A FORWARD_USER_P2P_TO_VETH_%i -j REJECT --reject-with icmp-admin-prohibited
PostUp = iptables -A FORWARD_USER_P2P_TO_WG_%i -p tcp -m multiport --sports 53,80,443 -j ACCEPT
PostUp = iptables -A FORWARD_USER_P2P_TO_WG_%i -p udp -m multiport --sports 53,443 -j ACCEPT
PostUp = iptables -A FORWARD_USER_P2P_TO_WG_%i -j DROP
PostUp = ip6tables -A FORWARD_P2P_TO_VETH_%i -j SET --add-set UserP2Pv6%i src --exist
PostUp = ip6tables -A FORWARD_P2P_TO_VETH_%i -j NFLOG --nflog-prefix FORWARD_P2P_TO_VETH_%i --nflog-group 2 --nflog-size 1500 --nflog-threshold 64
PostUp = ip6tables -A FORWARD_P2P_TO_VETH_%i -j REJECT --reject-with icmp6-adm-prohibited
PostUp = ip6tables -A FORWARD_P2P_TO_WG_%i -j SET --add-set UserP2Pv6%i dst --exist
PostUp = ip6tables -A FORWARD_P2P_TO_WG_%i -j NFLOG --nflog-prefix FORWARD_P2P_TO_WG_%i --nflog-group 3 --nflog-size 1500 --nflog-threshold 64
PostUp = ip6tables -A FORWARD_P2P_TO_WG_%i -j DROP
PostUp = ip6tables -A FORWARD_USER_P2P_TO_VETH_%i -p tcp -m multiport --dports 53,80,443 -j ACCEPT
PostUp = ip6tables -A FORWARD_USER_P2P_TO_VETH_%i -p udp -m multiport --dports 53,443 -j ACCEPT
PostUp = ip6tables -A FORWARD_USER_P2P_TO_VETH_%i -j REJECT --reject-with icmp6-adm-prohibited
PostUp = ip6tables -A FORWARD_USER_P2P_TO_WG_%i -p tcp -m multiport --sports 53,80,443 -j ACCEPT
PostUp = ip6tables -A FORWARD_USER_P2P_TO_WG_%i -p udp -m multiport --sports 53,443 -j ACCEPT
PostUp = ip6tables -A FORWARD_USER_P2P_TO_WG_%i -j DROP
# Ban portscan
PostUp = ipset create PortScanners%i hash:ip family inet hashsize 32768 maxelem 65536 timeout 600
PostUp = ipset create ScannedPorts%i hash:ip,port family inet hashsize 32768 maxelem 65536 timeout 60
PostUp = iptables -I FORWARD 1 -m state --state INVALID -j DROP
PostUp = iptables -I FORWARD 2 -m state --state NEW -m set ! --match-set ScannedPorts%i src,dst -m hashlimit --hashlimit-above 1/hour --hashlimit-burst 5 --hashlimit-mode srcip --hashlimit-name portscan --hashlimit-htable-expire 10000 -j SET --add-set PortScanners%i src --exist
PostUp = iptables -I FORWARD 3 -m state --state NEW -m set --match-set PortScanners%i src -j DROP
PostUp = iptables -I FORWARD 4 -m state --state NEW -j SET --add-set ScannedPorts%i src,dst
### Interface release
PreDown = iptables -D FORWARD -i %i -o ${ext_if} -j ACCEPT
PreDown = iptables -D FORWARD -o %i -i ${ext_if} -j ACCEPT
PreDown = ip6tables -D FORWARD -i %i -o ${ext_if} -j ACCEPT
PreDown = ip6tables -D FORWARD -o %i -i ${ext_if} -j ACCEPT
PreDown = iptables -t nat -D POSTROUTING -o ${ext_if} -j MASQUERADE
PreDown = ip6tables -t nat -D POSTROUTING -o ${ext_if} -j MASQUERADE
PreDown = iptables -D FORWARD -i %i -p tcp -m multiport --dports 25,137,139 -j DROP
PreDown = iptables -D FORWARD -i %i -p udp -m multiport --dports 137,138 -j DROP
PreDown = ip6tables -D FORWARD -i %i -p tcp -m multiport --dports 25,137,139 -j DROP
PreDown = ip6tables -D FORWARD -i %i -p udp -m multiport --dports 137,138 -j DROP
PreDown = iptables -D INPUT -d ${ext_ip} -p udp -m udp --dport 51820 -j ACCEPT
PreDown = iptables -t nat -D PREROUTING -i %i -p udp --dport 53 -j DNAT --to 1.1.1.1
PreDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport 53 -j DNAT --to 1.1.1.1
PreDown = ip6tables -t nat -D PREROUTING -i %i -p udp --dport 53 -j DNAT --to 2606:4700:4700::1111
PreDown = ip6tables -t nat -D PREROUTING -i %i -p tcp --dport 53 -j DNAT --to 2606:4700:4700::1111
PreDown = true && while [ $? -eq 0 ]; do iptables -D FORWARD -i %i -o ${ext_if} -j DROP 2>/dev/null; done || true
PreDown = true && while [ $? -eq 0 ]; do ip6tables -D FORWARD -i %i -o ${ext_if} -j DROP 2>/dev/null; done || true
# Torrent blocking
PreDown = iptables -D FORWARD -i %i -o ${ext_if} -m ipp2p --bit -g FORWARD_P2P_TO_VETH_%i
PreDown = iptables -D FORWARD -i %i -o ${ext_if} -m set --match-set UserP2Pv4%i src -g FORWARD_USER_P2P_TO_VETH_%i
PreDown = iptables -D FORWARD -o %i -i ${ext_if} -m ipp2p --bit -g FORWARD_P2P_TO_WG_%i
PreDown = iptables -D FORWARD -o %i -i ${ext_if} -m set --match-set UserP2Pv4%i dst -g FORWARD_USER_P2P_TO_WG_%i
PreDown = ip6tables -D FORWARD -i %i -o ${ext_if} -m ipp2p --bit -g FORWARD_P2P_TO_VETH_%i
PreDown = ip6tables -D FORWARD -i %i -o ${ext_if} -m set --match-set UserP2Pv6%i src -g FORWARD_USER_P2P_TO_VETH_%i
PreDown = ip6tables -D FORWARD -o %i -i ${ext_if} -m ipp2p --bit -g FORWARD_P2P_TO_WG_%i
PreDown = ip6tables -D FORWARD -o %i -i ${ext_if} -m set --match-set UserP2Pv6%i dst -g FORWARD_USER_P2P_TO_WG_%i
PreDown = iptables -F FORWARD_P2P_TO_VETH_%i
PreDown = iptables -F FORWARD_P2P_TO_WG_%i
PreDown = iptables -F FORWARD_USER_P2P_TO_VETH_%i
PreDown = iptables -F FORWARD_USER_P2P_TO_WG_%i
PreDown = ip6tables -F FORWARD_P2P_TO_VETH_%i
PreDown = ip6tables -F FORWARD_P2P_TO_WG_%i
PreDown = ip6tables -F FORWARD_USER_P2P_TO_VETH_%i
PreDown = ip6tables -F FORWARD_USER_P2P_TO_WG_%i
PreDown = iptables -X FORWARD_P2P_TO_VETH_%i
PreDown = iptables -X FORWARD_P2P_TO_WG_%i
PreDown = iptables -X FORWARD_USER_P2P_TO_VETH_%i
PreDown = iptables -X FORWARD_USER_P2P_TO_WG_%i
PreDown = ip6tables -X FORWARD_P2P_TO_VETH_%i
PreDown = ip6tables -X FORWARD_P2P_TO_WG_%i
PreDown = ip6tables -X FORWARD_USER_P2P_TO_VETH_%i
PreDown = ip6tables -X FORWARD_USER_P2P_TO_WG_%i
PreDown = ipset destroy UserP2Pv4%i
PreDown = ipset destroy UserP2Pv6%i
# Traffic control
PreDown = tc qdisc del dev %i root
PreDown = tc qdisc del dev %i handle ffff: ingress
# Ban portscan
PreDown = iptables -D FORWARD -m state --state INVALID -j DROP
PreDown = iptables -D FORWARD -m state --state NEW -m set ! --match-set ScannedPorts%i src,dst -m hashlimit --hashlimit-above 1/hour --hashlimit-burst 5 --hashlimit-mode srcip --hashlimit-name portscan --hashlimit-htable-expire 10000 -j SET --add-set PortScanners%i src --exist
PreDown = iptables -D FORWARD -m state --state NEW -m set --match-set PortScanners%i src -j DROP
PreDown = iptables -D FORWARD -m state --state NEW -j SET --add-set ScannedPorts%i src,dst
PreDown = ipset destroy PortScanners%i
PreDown = ipset destroy ScannedPorts%i
